### ISSUE TITLE
Need .deb pack for Ubuntu 15.10 x64 

### ISSUE THREAD

**Issue by AngryPenguinPL** [kolasa/fglrx-15.30.1025#1]
Hi.

Maybe this is not a issues but I need generated .deb pack with kolasa patch (for supporting new kernel). Can anyone make this deb pack for me?

**Comment by kolasa** [comment]
http://support.amd.com/en-us/download/desktop?os=Ubuntu+x86+64
install, apply patch, reinstall kernel headers

**Comment by AngryPenguinPL** [comment]
When I try reinstall kernel headers I have error (like from install time)
"Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.2.0-18-generic /boot/vmlinuz-4.2.0-18-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/fglrx-core.0.crash'
Error! Bad return status for module build on kernel: 4.2.0-18-generic (x86_64)
Consult /var/lib/dkms/fglrx-core/15.300/build/make.log for more information.
"

In log file:

DKMS make.log for fglrx-core-15.300 for kernel 4.2.0-18-generic (x86_64)
nie, 29 lis 2015, 00:46:07 CET
/usr/sbin/dkms: linia 74: cd: /var/lib/dkms/fglrx/15.30.1025/build: Nie ma takiego pliku ani katalogu
make.sh: 1: make.sh: gcc-5.2: not found
make.sh: 50: [: !=: unexpected operator
AMD kernel module generator version 2.1
doing Makefile based build for kernel 2.6.x and higher
rm -rf _.c *.h *.o *.ko *.a .??_ _.symvers
make -C /lib/modules/4.2.0-18-generic/build SUBDIRS=/var/lib/dkms/fglrx-core/15.300/build/2.6.x modules
make[1]: Wejście do katalogu '/usr/src/linux-headers-4.2.0-18-generic'
arch/x86/Makefile:123: stack-protector enabled but compiler support broken
arch/x86/Makefile:138: CONFIG_X86_X32 enabled but no binutils support
Makefile:669: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
make[1]: gcc-5.2: Polecenie nie znalezione
  CC [M]  /var/lib/dkms/fglrx-core/15.300/build/2.6.x/firegl_public.o
/bin/sh: 1: gcc-5.2: not found
scripts/Makefile.build:258: polecenia dla obiektu '/var/lib/dkms/fglrx-core/15.300/build/2.6.x/firegl_public.o' nie powiodły się
make[2]: *_\* [/var/lib/dkms/fglrx-core/15.300/build/2.6.x/firegl_public.o] Błąd 127
Makefile:1398: polecenia dla obiektu '_module_/var/lib/dkms/fglrx-core/15.300/build/2.6.x' nie powiodły się
make[1]: **\* [_module_/var/lib/dkms/fglrx-core/15.300/build/2.6.x] Błąd 2
make[1]: Opuszczenie katalogu '/usr/src/linux-headers-4.2.0-18-generic'
Makefile:88: polecenia dla obiektu 'kmod_build' nie powiodły się
make: **\* [kmod_build] Błąd 2
build failed with return value 2

Any solution?

**Comment by kolasa** [comment]
---

## /bin/sh: 1: gcc-5.2: not found

gcc: not found ?????????

apt-get install build-essential, install gcc-5 ?

(polskie komunikaty błędów, odpowiem w języku komunikatów :) brakuje kompilatora lub innych potrzebnych bibliotek do kompilacji ( ???-dev), należy je doinstalować i wykonać polecenie :

sudo /etc/kernel/header_postinst.d/dkms 4.2.0-18-generic /boot/vmlinuz-4.2.0-18-generic

na kernelu 4.2.0 czysty sterownik 15.30 instaluje się bez pojego patch'a bez problemu, patch potrzebny jest do 4.3 i 4.4 i zaręczam, że działa OK na karcie R290, problem jest na HD-6000 tutaj wywalenie przy starcie kernela i to jest ewidentnie wina AMD i ich biblioteki z zamknietym kodem a nie kernela, po prostu nie określili poprawnie jakie najstarsze karty obsługuje ten najnowszy sterownik)

**Comment by AngryPenguinPL** [comment]
Mam zainstalowane GCC5 i build-essential. Instalowałem wcześniej też paczki z solucji:
http://wiki.cchtml.com/index.php/Ubuntu_Trusty_Installation_Guide

czyli: 
sudo apt-get install cdbs dh-make dkms execstack dh-modaliases linux-headers-generic libqtgui4 xserver-xorg-dev
sudo apt-get install lib32gcc1

Na Ubuntu 15.04 działało bez problemów. Po aktualizacji do 15.10 są problemy. To wyglądało na kompilacyjny problem z gcc5, a więc wklepałem sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc (tak jak w jednym poradniku instalacji fglrx 15.9 na Ubuntu 15.10 - aby ominąć problem kompatybilności z GCC5).
Jak widać coś dalej jest nie tak. Zarówno na GCC4.8 jak i po przywróceniu GCC5 jest tak samo...
Myślałem, że to coś z generowanymi u mnie paczkami, dlatego chciałem "cudze" deby, ale po pobraniu paczek z amd.com dla ubuntu 14.04 jest tak samo.

EDIT:

Zresztą na Catalyst 15.9 przy próbie instalacji wygenerowanych paczek jest tak samo... Chce mieć własne paczki dlatego, że na tych z repo systemowego nie działa VAAPI - coś jest nie tak w tym buildzie, a wersje robione "ręcznie" VAAPI działa bez problemu.

**Comment by kolasa** [comment]
To wygląda na problem z kompilatorem i bibliotekami, warto spróbować zrobić purge fglrx_, po tych wszystkich instalacjach kompilatorów itp., wywalić jeżeli w /usr/src i /var/lib/dkms pozostało coś po fglrx i  ponownie deby zainstalować lub jeszcze lepiej poprzez pełny instalator AMD i na kernelu oryginalnym od Ubuntu 4.2.0-18/19 , tak u mnie zadziałało bez problemu, a potem na tych źródłach nakładać patche.
Ten komunikat:
Consult /var/lib/dkms/fglrx-core/15.300/build/make.log for more information
nie ma zgodności z tym komunikatem:
/usr/sbin/dkms: linia 74: cd: /var/lib/dkms/fglrx/15.30.1025/build: Nie ma takiego pliku ani katalogu
foldery się nie zgadzają, sugeruje delikatnie że deby fglrx_ nie są prawidłowo zainstalowane lub było kilka różnych prób instalacji, różnych debów( musi być zainstalowany komplet  debów fglrx )

**Comment by AngryPenguinPL** [comment]
Masz rację, dzięki :) 

Polecenie sudo apt-get purge fglrx i sudo apt-get remove fglrx\* usunęło sterowniki. Wyczyściłem var/lib/dkms i usr/src (były szczątki starych driverów). Uruchomiłem ponownie system na otwartych sterownikach i zainstalowałem fglrx 15.30 z paczek deb dla ubuntu 14.04 ze strony amd.
Instalacja przeszła ok, system wstał, sterownik działa ale z pewnym dziwolągiem.

Wersja sterownika jest ok, tzn 15.30.3, ale już wersja pakietu sterowników jest stara tzn. 15.201...
Tak przynajmniej podaje graficzne amdcccle.

Czy to może mieć związek z tym, że używam niewspieranej karty? Mobility Radeon HD5650M?

**Comment by kolasa** [comment]
ciekawie się robi coraz bardziej na mojej HD6470M w laptopie jest wielki oops na starcie systemu we wczesnej fazie a tutaj działa HD5650M :), zamykam sprawę kompilacji otwarte pozostaje pytanie jakie karty ten sterownik w końcu obsługuje i w jakiej wersji, w miarę nowe karty np. R290 chodzą OK, nawet można przejść do konsoli bez problemu chociaż z pewną bezwładnością przejścia a wcześniej konsola nie działała od kilku wersji a przynajmniej u mnie, co eliminowało te sterowniki w mojej pracy.
