### ISSUE TITLE
XPSTATE_FP and kernel-4.4

### ISSUE THREAD

**Issue by donahue95** [kolasa/fglrx-15.30.1025#2]
It appears XPSTATE_FP no longer exists in the 4.4 series kernels based on a 'grep -r XPSTATE_FP' of /usr/src which contained several 4.3 and several 4.4.  XPSTATE_FP was found in all the 4.3 but in none of the 4.4.
Result: 
/var/tmp/portage/x11-drivers/ati-drivers-15.12/work/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c: In function ‘KCL_fpu_save_init’:
/var/tmp/portage/x11-drivers/ati-drivers-15.12/work/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c:6505:49: merror: ‘XSTATE_FP’ undeclared (first use in this function)
       if (!(fpu->state.xsave.header.xfeatures & XSTATE_FP))
                                                 ^
/var/tmp/portage/x11-drivers/ati-drivers-15.12/work/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c:6505:49: note: each undeclared identifier is reported only once for each function it appears in
Causing build to fail.

**Comment by kolasa** [comment]
revised and corrected again for 15.30.1025 a long time ago:
https://github.com/kolasa/fglrx-15.30.1025/commit/0a83fc1f1fffed7205aa816794ab63b04dcdb38e

??? /var/tmp/portage/x11-drivers/ati-drivers-15.12 ???

fglrx 15.12 ?

**Comment by donahue95** [comment]
Working in Gentoo. Thus different names. 
Believe the problem will be OS agnostic.
Bothering you as you seem to get it right the earliest.

**Comment by faenil** [comment]
Edit: misread the latest commit ;)

**Comment by kolasa** [comment]
On 09.03.2016 23:38, faenil wrote:

> hi kolasa, why was this issue closed?
> 
> Your patch changed XP to FP, but FP does not exist in 4.4 kernels
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/kolasa/fglrx-15.30.1025/issues/2#issuecomment-194546538.
> 
> closed long ago, the mere spelling mistake XP and FP before kernel 4.4, as of today do not do anything with these drivers because the latest versions ceased to handle my graphics card and besides Canonical today fglrx sent to hell:

http://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-16.04-Dropping-fglrx

Krzysztof

**Comment by faenil** [comment]
Yeah, I read the news, although I think I still need fglrx, let's see if it works here...

thanks to your patch I could build the DKMS module, let's see if it works out :)
